### ISSUE TITLE
False-positive "unused lexical variable" with "local $Foo::bar = ..."

### ISSUE THREAD

**Issue by nthykier** [hurricup/Perl5-IDEA#780]
Hi,

Some module have "config variables", where it is common to "scope" then using local.  An example is Text::Wrap.

```perl
use Text::Wrap;

sub foo {
    local $Text::Wrap::huge = 'overflow';
    for my $t (split_paragraphs(@_)) {
       ...;
    }
}
```

The IntelliJ module flags $Text::Wrap::huge as an unused lexical variable, but "local" is not a lexicial variable (and notably, it is used inside "split_pararaphs" from Text::Wrap").

**Comment by hurricup** [comment]
This has been fixed at https://github.com/hurricup/Perl5-IDEA/issues/533 and should work fine in last release 1.218
If you are using IDEA14 platform, you may try current dev build, which is compatible with idea14 or wait for the next release.

**Comment by nthykier** [comment]
Alexandr Evstigneev:
> This has been fixed at https://github.com/hurricup/Perl5-IDEA/issues/533 and should work fine in last release 1.218
> If you are using IDEA14 platform, you may try current dev build, which is compatible with idea14 or wait for the next release.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hurricup/Perl5-IDEA/issues/780#issuecomment-173450442
> 

Hi,

I am still seeing the issue with IntelliJ 15.0.3 with Camelcade version
1.218.  Please see attached pngs.

The full file is available from [1], in case it helps debugging the issue.

Thanks,
~Niels

[1]
https://anonscm.debian.org/cgit/lintian/lintian.git/tree/lib/Lintian/Tag/TextUtil.pm

**Comment by hurricup** [comment]
Not sure how happened that this fix not reached 1.2, but it's fixed in 1.3 for sure: http://joxi.ru/bmooLD5hMOb6jm.png

So you may wait till 1.3 release or use a dev build.

**Comment by hurricup** [comment]
Problem re-appeared
